version: '3.8'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app 
    ports:
      - "3000:3000" 
    env_file: 
      - .env
    command: npm run start:dev

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: {}
