version: '3.8'

services:
  api:
    container_name: api
    build: ./src/api/
    volumes:
      - ./src/api/:/app 
    ports:
      - "3000:3000" 
    env_file: 
      - .env
    depends_on:
      - postgres
    command: npm run start:dev

  frontend:
    container_name: frontend
    build: ./src/frontend/
    volumes:
      - ./src/frontend/:/app
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: npm run start

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: {}
